# Generated by Django 3.1.2 on 2021-01-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('secondName', models.CharField(max_length=120)),
                ('lastName', models.CharField(blank=True, max_length=120, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('iin', models.CharField(blank=True, max_length=15, null=True)),
                ('national', models.CharField(blank=True, max_length=120, null=True)),
                ('citizen', models.CharField(blank=True, max_length=120, null=True)),
                ('PersonID', models.CharField(blank=True, max_length=120, null=True)),
                ('deathDate', models.DateField(blank=True, null=True)),
                ('hGBD', models.CharField(blank=True, max_length=120, null=True)),
                ('orgHealthCareId', models.CharField(blank=True, max_length=120, null=True)),
                ('personAddressesID', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('placeWork', models.CharField(blank=True, max_length=120, null=True)),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('telephoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('personStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('typeRecorded', models.CharField(blank=True, max_length=120, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sur.hospital')),
            ],
        ),
    ]
