# Generated by Django 3.1 on 2021-01-05 09:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210105_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasehistory',
            name='formData',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='diseasehistory',
            name='temporaryFormData',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
